services:
- type: web
  name: app_web
  runtime: python
  repo: https://github.com/Caren302/web-aplication
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python3 app.py
  rootDir: ./web
- type: web
  name: api_rest
  runtime: python
  repo: https://github.com/Caren302/api_rest
  plan: free
  region: oregon
  buildCommand: pip install "fastapi[standard]"
  startCommand: fastapi run main.py
  rootDir: ./app
version: "1"

databases:
  - name: agenda
    databaseName: agenda_db_p33n
    user: user
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: '16'
