services:
- type: web
  name: app_web
  runtime: python
  repo: https://github.com/Caren302/web-aplication
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python3 app.py
  rootDir: ./web
- type: web
  name: api_rest
  runtime: python
  repo: https://github.com/Caren302/api_rest
  plan: free
  region: oregon
  buildCommand: pip install "fastapi[standard]"
  startCommand: fastapi dev main.py
  rootDir: ./app
version: "1"